---
# ----------------------------------------
# Тестовый проектный файл Тулбар
# ----------------------------------------
project:
  start: main/usr.json  # файл - с которого можно начать чтение, в нем могут быть ссылки на другие файлы

  name: TOOLBAR   # уникальное имя проекта 


